### ISSUE TITLE
Incorrect link for Uninstall script

### ISSUE THREAD

**Issue by StevenDenman** [knom/vsts-office-tasks#2]
https://github.com/knom/vsts-office-tasks/blob/b823b8d69cb85d0e75cf138aa7bf9f26ac9cdba1/UninstallMailApp/task.json#L40

This should link to `UninstallMailApp.js` rather than `UninstallOutlookApp.js`

![image](https://user-images.githubusercontent.com/15671044/102622871-8c6fa380-4139-11eb-8ed1-62124f550f52.png)

**Comment by knom** [comment]
Finally.. @StevenDenman 
This is closed in #4 

Thanks for your contribution!

**Comment by knom** [comment]
@StevenDenman 
This is now RELEASED in marketplace as version 1.2.2.

Please test and let me know if you're fine.
