### ISSUE TITLE
What does this extension do?

### ISSUE THREAD

**Issue by dennisl68-castra** [knom/vsts-office-tasks#8]
I can't find any informations about what this extension is supposed to do or how you operate it once installed...

**Comment by oggy22** [comment]
@dennisl68-castra I am wondering the same :)

**Comment by knom** [comment]
Did you take a look at the README page?
https://github.com/knom/vsts-office-tasks#readme

Wondering what is unclear there ;-)
Please let me know..

The extension sideloads an OFFICE OUTLOOK ADDIN into O365 or Exchange..

**Comment by dennisl68-castra** [comment]
So, AzDOS kan essentially act as an Outlook-client with this add-in?

**Comment by knom** [comment]
Not as a client.

AzDO INSTALLS the ADD-IN into YOUR O365/Exchange tenant, so that it shows up in your Outlook client - e.g. Outlook Desktop, Outlook WebApp.
